# Generated by Django 4.2.10 on 2024-02-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_of_product',
            field=models.ImageField(null=True, upload_to='product_image'),
        ),
    ]
