# Generated by Django 4.2.10 on 2024-02-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_product_image_of_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_of_product',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/%y/%m/%d'),
        ),
    ]
